name: Deploy to EC2

on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Delete existing zip file
      run: rm -f strapi-app.zip

    - name: Zip files
      run: zip -r strapi-app.zip .

    - name: Copy files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        source: "strapi-app.zip"
        target: "/home/ubuntu"

    - name: SSH into EC2 and prepare environment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        script: |
          sudo apt-get update
          sudo apt-get install -y unzip docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          unzip /home/ubuntu/strapi-app.zip -d /home/ubuntu/strapi-app
          cd /home/ubuntu/strapi-app

          sudo docker ps -q | xargs -r sudo docker stop
          sudo docker rm $(sudo docker ps -aq)
          sudo docker rmi $(sudo docker images -q)
          sudo docker volume prune -f
          sudo docker network prune -f
          sudo docker system prune -a --volumes -f
          
          # Build and run the Docker container
          sudo docker build -t strapi-app .
          sudo docker run -d -p 1337:1337 strapi-app
